[versions]
agp = "8.3.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.0" }
androidx-multidex = { module = "androidx.multidex:multidex", version = "2.0.1" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-splashscreen = { module = "androidx.core:core-splashcreen", version = "1.0.1" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.2.0-alpha01" }
google-material = { module = "com.google.android.material:material", version = "1.13.0-alpha13" }

[bundles]
androidx = ["androidx-appcompat", "androidx-constraintlayout", "androidx-multidex", "androidx-preference"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }